<?php

namespace ContainerCx0xoWz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZN9ngJzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zN9ngJz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zN9ngJz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\WordRepository', 'getWordRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\WordRepository',
        ]);
    }
}
