<?php

namespace ContainerCx0xoWz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnagramControllerfindAnagramService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zN9ngJz.App\Controller\AnagramController::findAnagram()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zN9ngJz.App\\Controller\\AnagramController::findAnagram()'] = ($container->privates['.service_locator.zN9ngJz'] ?? $container->load('get_ServiceLocator_ZN9ngJzService'))->withContext('App\\Controller\\AnagramController::findAnagram()', $container);
    }
}
