<?php

namespace ContainerIPqaUDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWordImportControllerimportJsonService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YSugF_d.App\Controller\WordImportController::importJson()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YSugF_d.App\\Controller\\WordImportController::importJson()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\WordRepository', 'getWordRepositoryService', true],
            'importer' => ['privates', 'App\\Service\\Import\\WordImporter', 'getWordImporterService', true],
        ], [
            'repo' => 'App\\Repository\\WordRepository',
            'importer' => 'App\\Service\\Import\\WordImporter',
        ]))->withContext('App\\Controller\\WordImportController::importJson()', $container);
    }
}
