nelmio_api_doc:
    documentation:
        info:
            title: Anagram API
            description: PHP Symfony based API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        servers:
            -   url: http://localhost.com/unsafe
                description: API over HTTP
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
