<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCx0xoWz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCx0xoWz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCx0xoWz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCx0xoWz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCx0xoWz\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cx0xoWz',
    'container.build_id' => '2242f9e6',
    'container.build_time' => 1749458837,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCx0xoWz');
