<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'anagram_list' => [[], ['_controller' => 'App\\Controller\\AnagramController::findAnagram'], [], [['text', '/api/v1/anagram']], [], [], []],
    'wordbase_import' => [[], ['_controller' => 'App\\Controller\\WordImportController::import'], [], [['text', '/api/v1/words']], [], [], []],
    'wordbase_json_import' => [[], ['_controller' => 'App\\Controller\\WordImportController::importJson'], [], [['text', '/api/v1/wordsJson']], [], [], []],
    'wordbase_delete' => [[], ['_controller' => 'App\\Controller\\WordImportController::deleteDb'], [], [['text', '/api/v1/words']], [], [], []],
    'swagger_ui' => [[], ['_controller' => 'Nelmio\\ApiDocBundle\\Controller\\SwaggerUiAction::class'], [], [['text', '/api/doc']], [], [], []],
    'openapi_json' => [[], ['_controller' => 'Nelmio\\ApiDocBundle\\Controller\\SwaggerAction::class'], [], [['text', '/api/docs.json']], [], [], []],
];
