<?php

namespace ContainerF1gNe7T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnagramControllerfindAnagramService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.9LEDLXg.App\Controller\AnagramController::findAnagram()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9LEDLXg.App\\Controller\\AnagramController::findAnagram()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\WordRepository', 'getWordRepositoryService', true],
            'sortString' => ['privates', 'App\\Methods\\SortString', 'getSortStringService', true],
        ], [
            'repo' => 'App\\Repository\\WordRepository',
            'sortString' => 'App\\Methods\\SortString',
        ]))->withContext('App\\Controller\\AnagramController::findAnagram()', $container);
    }
}
