<?php

namespace ContainerF1gNe7T;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCsvImportStrategyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Import\CsvImportStrategy' shared autowired service.
     *
     * @return \App\Service\Import\Strategy\CsvImportStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Import/WordImportStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Import/CsvImportStrategy.php';

        return $container->privates['App\\Service\\Import\\Strategy\\CsvImportStrategy'] = new \App\Service\Import\Strategy\CsvImportStrategy();
    }
}
