<?php

namespace ContainerF1gNe7T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonImportStrategyService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Import\JsonImportStrategy' shared autowired service.
     *
     * @return \App\Service\Import\JsonImportStrategy
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Import/WordImportStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Import/JsonImportStrategy.php';

        return $container->privates['App\\Service\\Import\\JsonImportStrategy'] = new \App\Service\Import\JsonImportStrategy();
    }
}
