<?php

namespace ContainerF1gNe7T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSortStringService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Methods\SortString' shared autowired service.
     *
     * @return \App\Methods\SortString
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Methods/SortString.php';

        return $container->privates['App\\Methods\\SortString'] = new \App\Methods\SortString();
    }
}
