<?php

namespace ContainerF1gNe7T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWordImportControllerimportJsonService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.TckZ.0d.App\Controller\WordImportController::importJson()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TckZ.0d.App\\Controller\\WordImportController::importJson()'] = ($container->privates['.service_locator.TckZ.0d'] ?? $container->load('get_ServiceLocator_TckZ_0dService'))->withContext('App\\Controller\\WordImportController::importJson()', $container);
    }
}
