<?php

namespace ContainerF1gNe7T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWordImporterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Import\WordImporter' shared autowired service.
     *
     * @return \App\Service\Import\WordImporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Import/WordImporter.php';

        return $container->privates['App\\Service\\Import\\WordImporter'] = new \App\Service\Import\WordImporter(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Service\\Import\\CsvImportStrategy'] ??= new \App\Service\Import\CsvImportStrategy());
            yield 1 => ($container->privates['App\\Service\\Import\\JsonImportStrategy'] ??= new \App\Service\Import\JsonImportStrategy());
            yield 2 => ($container->privates['App\\Service\\Import\\TextImportStrategy'] ??= new \App\Service\Import\TextImportStrategy());
        }, 3), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
