<?php

namespace ContainerDUMdMPL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWordImportControllerdeleteDbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zN9ngJz.App\Controller\WordImportController::deleteDb()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zN9ngJz.App\\Controller\\WordImportController::deleteDb()'] = ($container->privates['.service_locator.zN9ngJz'] ?? $container->load('get_ServiceLocator_ZN9ngJzService'))->withContext('App\\Controller\\WordImportController::deleteDb()', $container);
    }
}
